# Generated by Django 6.0.3 on 2026-03-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coctails_app', '0007_cocktailingredient_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cocktail',
            old_name='author',
            new_name='author_id',
        ),
        migrations.RenameField(
            model_name='cocktail',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='cocktail',
            old_name='ingredients',
            new_name='ingredient_id',
        ),
        migrations.RenameField(
            model_name='cocktailingredient',
            old_name='author',
            new_name='author_id',
        ),
        migrations.RenameField(
            model_name='cocktailingredient',
            old_name='cocktail',
            new_name='cocktail_id',
        ),
        migrations.RenameField(
            model_name='cocktailingredient',
            old_name='ingredient',
            new_name='ingredient_id',
        ),
    ]
