# Generated by Django 6.0.3 on 2026-03-19 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coctails_app', '0008_rename_author_cocktail_author_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='cocktail',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='cocktail',
            name='ingredient_id',
        ),
        migrations.RemoveField(
            model_name='cocktailingredient',
            name='author_id',
        ),
        migrations.AddField(
            model_name='cocktail',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cocktails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coctails_app.category'),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='ingredients',
            field=models.ManyToManyField(through='coctails_app.CocktailIngredient', to='coctails_app.ingredient'),
        ),
        migrations.AddField(
            model_name='cocktailingredient',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cocktail_ingredients', to=settings.AUTH_USER_MODEL),
        ),
    ]
