# Generated by Django 6.0.3 on 2026-03-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coctails_app', '0009_remove_cocktail_author_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cocktailingredient',
            old_name='cocktail_id',
            new_name='cocktail',
        ),
        migrations.RenameField(
            model_name='cocktailingredient',
            old_name='ingredient_id',
            new_name='ingredient',
        ),
    ]
