# Generated by Django 6.0.3 on 2026-03-19 17:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coctails_app', '0011_category_author_alter_ingredient_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.URLField(blank=True, help_text='URL to the image of ingredient', null=True),
        ),
        migrations.AddConstraint(
            model_name='cocktailingredient',
            constraint=models.UniqueConstraint(fields=('cocktail', 'ingredient'), name='unique_cocktail_ingredient'),
        ),
    ]
